version: '3.8'

services:
  app-frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:8000/api/:path*
    command: 
      - sh
      - -c
      - "node --run build && node --run start" 
      # Desarrollo: - "node --run dev"