import './globals.css'
import Navbar from '@/app/_components/ui/Navbar'
import LoginModal from '@/app/_components/form/LoginModal'
import Sidebar from '@/app/_components/ui/sidebar/Sidebar'
import { AuthProvider } from './_contexts/auth'
import { FiltersProvider } from '@/app/_contexts/filters'
import { CategoriesProvider } from '@/app/_contexts/categories'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({ children }) {
  return (
    <html lang='es'>
      <body className='flex h-full'>
        <AuthProvider>
          <CategoriesProvider>
            <FiltersProvider>
              <Navbar />
              <Sidebar />
              <LoginModal />
              {children}
            </FiltersProvider>
          </CategoriesProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
